[setup]
connected_boards = ["TCM0", "PMA0"]
reset_system = true
manager_start = true
reset_errors = true
status_tracking = true                                                                                                     # all connected boards
configuration = "laser_1124hz_or_trg"
wait_for_attenuator = true
counter_rates_tracking = true
bad_channel_map = { expected_rate = 1000.0, lower_tolerance = 0.1, upper_tolerance = 0.1, reference_channel = "PMA0CH12" }

[tests]
parameters = ["TCM0", "PMA0"]     # equivalent to true here
histograms = ["TCM0", "PMA0"]
main_sleep = 10.0
read_interval_change = true
reset_counters = ["TCM0", "PMA0"]

[cleanup]
reset_errors = false
configuration = false
