[setup]
connected_boards = ["TCM0", "PMA0"]
reset_system = true
manager_start = true
reset_errors = true
status_tracking = true # all connected boards
configuration = "laser_1124hz_or_trg"
counter_rates_tracking = true

[tests]
parameters = ["TCM0", "PMA0"] # equivalent to true here
histograms = ["TCM0", "PMA0"]
main_sleep = 10.0
read_interval_change = true
reset_counters = ["TCM0", "PMA0"]

[cleanup]
reset_errors = false
configuration = false
