[setup]
connected_boards = [ "TCM0", "PMA0" ]
reset_system = true
manager_start = true
reset_errors = true
status_tracking = true
configuration = false
counter_rates_tracking = true

[tests]
parameters = true
histograms = false
main_sleep = 3.0
read_interval_change = false
reset_counters = false

[cleanup]
reset_errors = false
configuration = false
