[setup]
connected_boards = [ "TCM0", "PMA0" ]
reset_system = false
reset_errors = false
status_tracking = true
configuration = false
counter_rates_tracking = true

[tests]
parameters = false
histograms = false
main_sleep = 3.0
read_interval_change = false
reset_counters = false

[cleanup]
reset_errors = false
configuration = false
